name: Delete old packages
on:
  schedule:
    - cron: '0 7 * * 6'
  workflow_dispatch:
permissions:
  packages: write

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    if: github.repository == 'letsblockit/letsblockit'
    steps:
    - uses: actions/delete-package-versions@v5
      with:
        owner: letsblockit
        package-name: server-dev
        package-type: container
        min-versions-to-keep: 40
